/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiTestRouteImport } from './routes/api-test'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiV1InvoicesRouteImport } from './routes/api/v1/invoices'
import { Route as ApiV1ExtractRouteImport } from './routes/api/v1/extract'
import { Route as ApiV1UsageCurrentRouteImport } from './routes/api/v1/usage.current'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api-test',
  path: '/api-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiV1InvoicesRoute = ApiV1InvoicesRouteImport.update({
  id: '/api/v1/invoices',
  path: '/api/v1/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExtractRoute = ApiV1ExtractRouteImport.update({
  id: '/api/v1/extract',
  path: '/api/v1/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UsageCurrentRoute = ApiV1UsageCurrentRouteImport.update({
  id: '/api/v1/usage/current',
  path: '/api/v1/usage/current',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/auth': typeof AuthRoute
  '/extract': typeof ExtractRoute
  '/upload': typeof UploadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/v1/extract': typeof ApiV1ExtractRoute
  '/api/v1/invoices': typeof ApiV1InvoicesRoute
  '/api/v1/usage/current': typeof ApiV1UsageCurrentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/auth': typeof AuthRoute
  '/extract': typeof ExtractRoute
  '/upload': typeof UploadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/v1/extract': typeof ApiV1ExtractRoute
  '/api/v1/invoices': typeof ApiV1InvoicesRoute
  '/api/v1/usage/current': typeof ApiV1UsageCurrentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api-test': typeof ApiTestRoute
  '/auth': typeof AuthRoute
  '/extract': typeof ExtractRoute
  '/upload': typeof UploadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/v1/extract': typeof ApiV1ExtractRoute
  '/api/v1/invoices': typeof ApiV1InvoicesRoute
  '/api/v1/usage/current': typeof ApiV1UsageCurrentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-test'
    | '/auth'
    | '/extract'
    | '/upload'
    | '/admin'
    | '/api/v1/extract'
    | '/api/v1/invoices'
    | '/api/v1/usage/current'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-test'
    | '/auth'
    | '/extract'
    | '/upload'
    | '/admin'
    | '/api/v1/extract'
    | '/api/v1/invoices'
    | '/api/v1/usage/current'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api-test'
    | '/auth'
    | '/extract'
    | '/upload'
    | '/_authenticated/admin'
    | '/api/v1/extract'
    | '/api/v1/invoices'
    | '/api/v1/usage/current'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiTestRoute: typeof ApiTestRoute
  AuthRoute: typeof AuthRoute
  ExtractRoute: typeof ExtractRoute
  UploadRoute: typeof UploadRoute
  ApiV1ExtractRoute: typeof ApiV1ExtractRoute
  ApiV1InvoicesRoute: typeof ApiV1InvoicesRoute
  ApiV1UsageCurrentRoute: typeof ApiV1UsageCurrentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-test': {
      id: '/api-test'
      path: '/api-test'
      fullPath: '/api-test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/invoices': {
      id: '/api/v1/invoices'
      path: '/api/v1/invoices'
      fullPath: '/api/v1/invoices'
      preLoaderRoute: typeof ApiV1InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/extract': {
      id: '/api/v1/extract'
      path: '/api/v1/extract'
      fullPath: '/api/v1/extract'
      preLoaderRoute: typeof ApiV1ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/usage/current': {
      id: '/api/v1/usage/current'
      path: '/api/v1/usage/current'
      fullPath: '/api/v1/usage/current'
      preLoaderRoute: typeof ApiV1UsageCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiTestRoute: ApiTestRoute,
  AuthRoute: AuthRoute,
  ExtractRoute: ExtractRoute,
  UploadRoute: UploadRoute,
  ApiV1ExtractRoute: ApiV1ExtractRoute,
  ApiV1InvoicesRoute: ApiV1InvoicesRoute,
  ApiV1UsageCurrentRoute: ApiV1UsageCurrentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
